export interface Quote {
  id: number;
  quoteText: string;
  attributedAuthor: string;
}

export const quotes: Quote[] = [
  { id: 1, quoteText: 'The only way to do great work is to love what you do.', attributedAuthor: 'Steve Jobs' },
  { id: 2, quoteText: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', attributedAuthor: 'Winston Churchill' },
  { id: 3, quoteText: 'The mind is everything. What you think you become.', attributedAuthor: 'Buddha' },
  { id: 4, quoteText: 'Don\'t let yesterday take up too much of today.', attributedAuthor: 'Will Rogers' },
  { id: 5, quoteText: 'The road to success and the road to failure are almost exactly the same.', attributedAuthor: 'Colin R. Davis' },
  { id: 6, quoteText: 'Believe you can and you\'re halfway there.', attributedAuthor: 'Theodore Roosevelt' },
  { id: 7, quoteText: 'It does not matter how slowly you go as long as you do not stop.', attributedAuthor: 'Confucius' },
  { id: 8, quoteText: 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', attributedAuthor: 'Thomas A. Edison' },
  { id: 9, quoteText: 'The future belongs to those who believe in the beauty of their dreams.', attributedAuthor: 'Eleanor Roosevelt' },
  { id: 10, quoteText: 'It is never too late to be what you might have been.', attributedAuthor: 'George Eliot' },
  { id: 11, quoteText: 'You learn more from failure than from success. Don\'t let it stop you. Failure builds character.', attributedAuthor: 'Unknown' },
  { id: 12, quoteText: 'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', attributedAuthor: 'Winston Churchill' },
  { id: 13, quoteText: 'If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.', attributedAuthor: 'Steve Jobs' },
  { id: 14, quoteText: 'It’s hard to beat a person who never gives up.', attributedAuthor: 'Babe Ruth' },
  { id: 15, quoteText: 'If people are doubting how far you can go, go so far that you can’t hear them anymore.', attributedAuthor: 'Michele Ruiz' },
  { id: 16, quoteText: 'Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.', attributedAuthor: 'Neil Gaiman' },
  { id: 17, quoteText: 'Do one thing every day that scares you.', attributedAuthor: 'Eleanor Roosevelt' },
  { id: 18, quoteText: 'Everything you can imagine is real.', attributedAuthor: 'Pablo Picasso' },
  { id: 19, quoteText: 'The only person you are destined to become is the person you decide to be.', attributedAuthor: 'Ralph Waldo Emerson' },
  { id: 20, quoteText: 'What you do speaks so loudly that I cannot hear what you say.', attributedAuthor: 'Ralph Waldo Emerson' },
  { id: 21, quoteText: 'I have not failed. I\'ve just found 10,000 ways that won\'t work.', attributedAuthor: 'Thomas A. Edison' },
  { id: 22, quoteText: 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', attributedAuthor: 'David Brinkley' },
  { id: 23, quoteText: 'I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.', attributedAuthor: 'Michael Jordan' },
  { id: 24, quoteText: 'The best time to plant a tree was 20 years ago. The second best time is now.', attributedAuthor: 'Chinese Proverb' },
  { id: 25, quoteText: 'An unexamined life is not worth living.', attributedAuthor: 'Socrates' },
  { id: 26, quoteText: 'Your time is limited, so don’t waste it living someone else’s life.', attributedAuthor: 'Steve Jobs' },
  { id: 27, quoteText: 'Winning isn’t everything, but wanting to win is.', attributedAuthor: 'Vince Lombardi' },
  { id: 28, quoteText: 'Whether you think you can or you think you can’t, you’re right.', attributedAuthor: 'Henry Ford' },
  { id: 29, quoteText: 'The two most important days in your life are the day you are born and the day you find out why.', attributedAuthor: 'Mark Twain' },
  { id: 30, quoteText: 'Either you run the day or the day runs you.', attributedAuthor: 'Jim Rohn' },
  { id: 31, quoteText: 'When we strive to become better than we are, everything around us becomes better too.', attributedAuthor: 'Paulo Coelho' },
  { id: 32, quoteText: 'Our greatest glory is not in never falling, but in rising every time we fall.', attributedAuthor: 'Confucius' },
  { id: 33, quoteText: 'The journey of a thousand miles begins with a single step.', attributedAuthor: 'Lao Tzu' },
  { id: 34, quoteText: 'It always seems impossible until it\'s done.', attributedAuthor: 'Nelson Mandela' },
  { id: 35, quoteText: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', attributedAuthor: 'Ralph Waldo Emerson' },
  { id: 36, quoteText: 'The only thing we have to fear is fear itself.', attributedAuthor: 'Franklin D. Roosevelt' },
  { id: 37, quoteText: 'I am not a product of my circumstances. I am a product of my decisions.', attributedAuthor: 'Stephen R. Covey' },
  { id: 38, quoteText: 'When you reach the end of your rope, tie a knot in it and hang on.', attributedAuthor: 'Franklin D. Roosevelt' },
  { id: 39, quoteText: 'The secret of getting ahead is getting started.', attributedAuthor: 'Mark Twain' },
  { id: 40, quoteText: 'You miss 100% of the shots you don\'t take.', attributedAuthor: 'Wayne Gretzky' },
  { id: 41, quoteText: 'Life is 10% what happens to you and 90% how you react to it.', attributedAuthor: 'Charles R. Swindoll' },
  { id: 42, quoteText: 'If you want to lift yourself up, lift up someone else.', attributedAuthor: 'Booker T. Washington' },
  { id: 43, quoteText: 'I\'ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', attributedAuthor: 'Maya Angelou' },
  { id: 44, quoteText: 'The most difficult thing is the decision to act, the rest is merely tenacity.', attributedAuthor: 'Amelia Earhart' },
  { id: 45, quoteText: 'Strive not to be a success, but rather to be of value.', attributedAuthor: 'Albert Einstein' },
  { id: 46, quoteText: 'Fall seven times and stand up eight.', attributedAuthor: 'Japanese Proverb' },
  { id: 47, quoteText: 'Everything has beauty, but not everyone sees it.', attributedAuthor: 'Confucius' },
  { id: 48, quoteText: 'A journey of a thousand miles begins with a single step.', attributedAuthor: 'Lao Tzu' },
  { id: 49, quoteText: 'What we achieve inwardly will change outer reality.', attributedAuthor: 'Plutarch' },
  { id: 50, quoteText: 'It is not in the stars to hold our destiny but in ourselves.', attributedAuthor: 'William Shakespeare' },
  { id: 51, quoteText: 'The only true wisdom is in knowing you know nothing.', attributedAuthor: 'Socrates' },
  { id: 52, quoteText: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', attributedAuthor: 'Aristotle' },
  { id: 53, quoteText: 'The secret of change is to focus all of your energy, not on fighting the old, but on building the new.', attributedAuthor: 'Socrates' },
  { id: 54, quoteText: 'If you\'re going through hell, keep going.', attributedAuthor: 'Winston Churchill' },
  { id: 55, quoteText: 'Life is like riding a bicycle. To keep your balance, you must keep moving.', attributedAuthor: 'Albert Einstein' },
  { id: 56, quoteText: 'That which does not kill us makes us stronger.', attributedAuthor: 'Friedrich Nietzsche' },
  { id: 57, quoteText: 'Nothing is impossible, the word itself says \'I\'m possible\'!', attributedAuthor: 'Audrey Hepburn' },
  { id: 58, quoteText: 'Start where you are. Use what you have. Do what you can.', attributedAuthor: 'Arthur Ashe' },
  { id: 59, quoteText: 'The best revenge is massive success.', attributedAuthor: 'Frank Sinatra' },
  { id: 60, quoteText: 'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination.', attributedAuthor: 'Jimmy Dean' },
  { id: 61, quoteText: 'We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', attributedAuthor: 'Marie Curie' },
  { id: 62, quoteText: 'The question isn\'t who is going to let me; it\'s who is going to stop me.', attributedAuthor: 'Ayn Rand' },
  { id: 63, quoteText: 'If you don\'t like the road you\'re walking, start paving another one.', attributedAuthor: 'Dolly Parton' },
  { id: 64, quoteText: 'You must do the thing you think you cannot do.', attributedAuthor: 'Eleanor Roosevelt' },
  { id: 65, quoteText: 'The only limit to our realization of tomorrow will be our doubts of today.', attributedAuthor: 'Franklin D. Roosevelt' },
  { id: 66, quoteText: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', attributedAuthor: 'Ralph Waldo Emerson' },
  { id: 67, quoteText: 'Turn your wounds into wisdom.', attributedAuthor: 'Oprah Winfrey' },
  { id: 68, quoteText: 'The best way to predict the future is to create it.', attributedAuthor: 'Abraham Lincoln' },
  { id: 69, quoteText: 'If you want to achieve greatness stop asking for permission.', attributedAuthor: 'Anonymous' },
  { id: 70, quoteText: 'To live is the rarest thing in the world. Most people exist, that is all.', attributedAuthor: 'Oscar Wilde' },
  { id: 71, quoteText: 'If you have a dream, you’ve got to grab it and never let go.', attributedAuthor: 'Carol Burnett' },
  { id: 72, quoteText: 'Hard work beats talent when talent doesn\'t work hard.', attributedAuthor: 'Tim Notke' },
  { id: 73, quoteText: 'If you set your goals ridiculously high and it\'s a failure, you will fail above everyone else\'s success.', attributedAuthor: 'James Cameron' },
  { id: 74, quoteText: 'Go the extra mile. It\'s never crowded there.', attributedAuthor: 'Dr. Wayne D. Dyer' },
  { id: 75, quoteText: 'Make each day your masterpiece.', attributedAuthor: 'John Wooden' },
  { id: 76, quoteText: 'Don\'t count the days, make the days count.', attributedAuthor: 'Muhammad Ali' },
  { id: 77, quoteText: 'The only impossible journey is the one you never begin.', attributedAuthor: 'Tony Robbins' },
  { id: 78, quoteText: 'In the middle of every difficulty lies opportunity.', attributedAuthor: 'Albert Einstein' },
  { id: 79, quoteText: 'Act as if what you do makes a difference. It does.', attributedAuthor: 'William James' },
  { id: 80, quoteText: 'You must be the change you wish to see in the world.', attributedAuthor: 'Mahatma Gandhi' },
  { id: 81, quoteText: 'It\'s not the years in your life that count. It\'s the life in your years.', attributedAuthor: 'Abraham Lincoln' },
  { id: 82, quoteText: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', attributedAuthor: 'Zig Ziglar' },
  { id: 83, quoteText: 'The best time to plant a tree was 20 years ago. The second best time is now.', attributedAuthor: 'Chinese Proverb' },
  { id: 84, quoteText: 'Your passion is waiting for your courage to catch up.', attributedAuthor: 'Isabelle Lafleche' },
  { id: 85, quoteText: 'If you can dream it, you can do it.', attributedAuthor: 'Walt Disney' },
  { id: 86, quoteText: 'I am the master of my fate, I am the captain of my soul.', attributedAuthor: 'William Ernest Henley' },
  { id: 87, quoteText: 'A person who never made a mistake never tried anything new.', attributedAuthor: 'Albert Einstein' },
  { id: 88, quoteText: 'The purpose of our lives is to be happy.', attributedAuthor: 'Dalai Lama' },
  { id: 89, quoteText: 'Get busy living or get busy dying.', attributedAuthor: 'Stephen King' },
  { id: 90, quoteText: 'You only live once, but if you do it right, once is enough.', attributedAuthor: 'Mae West' },
  { id: 91, quoteText: 'Never let the fear of striking out keep you from playing the game.', attributedAuthor: 'Babe Ruth' },
  { id: 92, quoteText: 'Life is a succession of lessons which must be lived to be understood.', attributedAuthor: 'Ralph Waldo Emerson' },
  { id: 93, quoteText: 'You have power over your mind — not outside events. Realize this, and you will find strength.', attributedAuthor: 'Marcus Aurelius' },
  { id: 94, quoteText: 'What seems to us as bitter trials are often blessings in disguise.', attributedAuthor: 'Oscar Wilde' },
  { id: 95, quoteText: 'The difference between ordinary and extraordinary is that little extra.', attributedAuthor: 'Jimmy Johnson' },
  { id: 96, quoteText: 'The best way out is always through.', attributedAuthor: 'Robert Frost' },
  { id: 97, quoteText: 'The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it.', attributedAuthor: 'Jordan Belfort' },
  { id: 98, quoteText: 'If you don\'t stand for something you will fall for anything.', attributedAuthor: 'Alexander Hamilton' },
  { id: 99, quoteText: 'The two most powerful warriors are patience and time.', attributedAuthor: 'Leo Tolstoy' },
  { id: 100, quoteText: 'There is nothing permanent except change.', attributedAuthor: 'Heraclitus' },
  { id: 101, quoteText: 'A ship in harbor is safe, but that is not what ships are built for.', attributedAuthor: 'John A. Shedd' },
  { id: 102, quoteText: 'Dream big and dare to fail.', attributedAuthor: 'Norman Vaughan' },
  { id: 103, quoteText: 'It is our choices that show what we truly are, far more than our abilities.', attributedAuthor: 'J.K. Rowling' },
  { id: 104, quoteText: 'Don\'t judge each day by the harvest you reap but by the seeds that you plant.', attributedAuthor: 'Robert Louis Stevenson' },
  { id: 105, quoteText: 'The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.', attributedAuthor: 'Ralph Waldo Emerson' },
  { id: 106, quoteText: 'You can\'t use up creativity. The more you use, the more you have.', attributedAuthor: 'Maya Angelou' },
  { id: 107, quoteText: 'The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.', attributedAuthor: 'Helen Keller' },
  { id: 108, quoteText: 'I attribute my success to this: I never gave or took any excuse.', attributedAuthor: 'Florence Nightingale' },
  { id: 109, quoteText: 'It is better to fail in originality than to succeed in imitation.', attributedAuthor: 'Herman Melville' },
  { id: 110, quoteText: 'The way to get started is to quit talking and begin doing.', attributedAuthor: 'Walt Disney' },
  { id: 111, quoteText: 'If you are not willing to risk the usual, you will have to settle for the ordinary.', attributedAuthor: 'Jim Rohn' },
  { id: 112, quoteText: 'You can\'t be that kid standing at the top of the waterslide, overthinking it. You have to go down the chute.', attributedAuthor: 'Tina Fey' },
  { id: 113, quoteText: 'I never dreamed about success. I worked for it.', attributedAuthor: 'Estée Lauder' },
  { id: 114, quoteText: 'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.', attributedAuthor: 'Helen Keller' },
  { id: 115, quoteText: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', attributedAuthor: 'Vince Lombardi' },
  { id: 116, quoteText: 'We cannot solve our problems with the same thinking we used when we created them.', attributedAuthor: 'Albert Einstein' },
  { id: 117, quoteText: 'A good plan violently executed now is better than a perfect plan executed next week.', attributedAuthor: 'George S. Patton' },
  { id: 118, quoteText: 'Twenty years from now you will be more disappointed by the things that you didn\'t do than by the ones you did do.', attributedAuthor: 'Mark Twain' },
  { id: 119, quoteText: 'The person who says it cannot be done should not interrupt the person who is doing it.', attributedAuthor: 'Chinese Proverb' },
  { id: 120, quoteText: 'Build your own dreams, or someone else will hire you to build theirs.', attributedAuthor: 'Farrah Gray' },
  { id: 121, quoteText: 'If you hear a voice within you say \'you cannot paint,\' then by all means paint, and that voice will be silenced.', attributedAuthor: 'Vincent van Gogh' },
  { id: 122, quoteText: 'Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.', attributedAuthor: 'Jamie Paolinetti' },
  { id: 123, quoteText: 'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.', attributedAuthor: 'Mark Caine' },
  { id: 124, quoteText: 'When I let go of what I am, I become what I might be.', attributedAuthor: 'Lao Tzu' },
  { id: 125, quoteText: 'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.', attributedAuthor: 'Charles Darwin' },
  { id: 126, quoteText: 'The best way to find yourself is to lose yourself in the service of others.', attributedAuthor: 'Mahatma Gandhi' },
  { id: 127, quoteText: 'If you want to go fast, go alone. If you want to go far, go together.', attributedAuthor: 'African Proverb' },
  { id: 128, quoteText: 'I have stood on a mountain of no\'s for one yes.', attributedAuthor: 'Barbara Elaine Smith' },
  { id: 129, quoteText: 'Don\'t be afraid to give up the good to go for the great.', attributedAuthor: 'John D. Rockefeller' },
  { id: 130, quoteText: 'The successful warrior is the average man, with laser-like focus.', attributedAuthor: 'Bruce Lee' },
  { id: 131, quoteText: 'There are no traffic jams along the extra mile.', attributedAuthor: 'Roger Staubach' },
  { id: 132, quoteText: 'Well done is better than well said.', attributedAuthor: 'Benjamin Franklin' },
  { id: 133, quoteText: 'You can\'t fall if you don\'t climb. But there\'s no joy in living your whole life on the ground.', attributedAuthor: 'Anonymous' },
  { id: 134, quoteText: 'If you\'re offered a seat on a rocket ship, don\'t ask what seat! Just get on.', attributedAuthor: 'Sheryl Sandberg' },
  { id: 135, quoteText: 'I am not what happened to me, I am what I choose to become.', attributedAuthor: 'Carl Jung' },
  { id: 136, quoteText: 'The difference between a stumbling block and a stepping stone is how you use it.', attributedAuthor: 'Anonymous' },
  { id: 137, quoteText: 'If you do what you\'ve always done, you\'ll get what you\'ve always gotten.', attributedAuthor: 'Tony Robbins' },
  { id: 138, quoteText: 'Don\'t wait for opportunity. Create it.', attributedAuthor: 'George Bernard Shaw' },
  { id: 139, quoteText: 'The comeback is always stronger than the setback.', attributedAuthor: 'Anonymous' },
  { id: 140, quoteText: 'The man on top of the mountain didn\'t fall there.', attributedAuthor: 'Vince Lombardi' },
  { id: 141, quoteText: 'If it doesn\'t challenge you, it doesn\'t change you.', attributedAuthor: 'Fred DeVito' },
  { id: 142, quoteText: 'The pain you feel today will be the strength you feel tomorrow.', attributedAuthor: 'Anonymous' },
  { id: 143, quoteText: 'Tough times never last, but tough people do.', attributedAuthor: 'Robert H. Schuller' },
  { id: 144, quoteText: 'A smooth sea never made a skilled sailor.', attributedAuthor: 'Franklin D. Roosevelt' },
  { id: 145, quoteText: 'It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving forward.', attributedAuthor: 'Sylvester Stallone' },
  { id: 146, quoteText: 'The greater the obstacle, the more glory in overcoming it.', attributedAuthor: 'Molière' },
  { id: 147, quoteText: 'It is during our darkest moments that we must focus to see the light.', attributedAuthor: 'Aristotle' },
  { id: 148, quoteText: 'A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.', attributedAuthor: 'Christopher Reeve' },
  { id: 149, quoteText: 'The human spirit is stronger than anything that can happen to it.', attributedAuthor: 'C.C. Scott' },
  { id: 150, quoteText: 'What the caterpillar calls the end of the world, the master calls a butterfly.', attributedAuthor: 'Richard Bach' },
];