// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dciiaeugcyvhgpyetceh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjaWlhZXVnY3l2aGdweWV0Y2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NzIxNjksImV4cCI6MjA3MDM0ODE2OX0.h8xbRY5P5Xl92e2sU5d9hJn4QpNrkUrPjsLYFswXCLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);